#DB 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # 파일 업로드 크기 제한 설정
  servlet:
    multipart:
      max-file-size: 10MB      # 업로드 가능한 단일 파일의 최대 크기
      max-request-size: 10MB   # 전체 요청의 최대 크기

file:
  upload-dir: src/main/resources/inquiryImg

# 파일 업로드 크기 제한 설정
server:
  tomcat:
    max-swallow-size: 10MB  # 톰캣의 최대 요청 크기 (10MB)

ssh:
  host:
  ssh_port: 22
  user:
  private_key:
  database_port: 3307
